services:
  db:
    image: postgres:15
    container_name: bicicletos-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - bicicletas_data:/var/lib/postgresql/data

volumes:
  bicicletas_data:
